In [2]:
import pandas as pd

In [3]:
match_path = "resources/data.csv"
fighter_path = "resources/raw_fighter_details.csv"

In [4]:
match_data = pd.read_csv("resources/data.csv")

In [9]:
match_columns = ['R_fighter','B_fighter','date','location','Winner','weight_class']

match_df = match_data[match_columns]
match_df.columns = ["red","blue","date","location","win_color","weight_class"]
match_df["winner"] = ""
match_df["loser"] = ""

match_df

C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\khiro\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,red,blue,date,location,win_color,weight_class,winner,loser
0,Henry Cejudo,Marlon Moraes,2019-06-08,"Chicago, Illinois, USA",Red,Bantamweight,,
1,Valentina Shevchenko,Jessica Eye,2019-06-08,"Chicago, Illinois, USA",Red,Women's Flyweight,,
2,Tony Ferguson,Donald Cerrone,2019-06-08,"Chicago, Illinois, USA",Red,Lightweight,,
3,Jimmie Rivera,Petr Yan,2019-06-08,"Chicago, Illinois, USA",Blue,Bantamweight,,
4,Tai Tuivasa,Blagoy Ivanov,2019-06-08,"Chicago, Illinois, USA",Blue,Heavyweight,,
...,...,...,...,...,...,...,...,...
5139,Gerard Gordeau,Kevin Rosier,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,,
5140,Ken Shamrock,Patrick Smith,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,,
5141,Royce Gracie,Art Jimmerson,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,,
5142,Kevin Rosier,Zane Frazier,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,,
5143,Gerard Gordeau,Teila Tuli,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,,

In [10]:
for index, row in match_df.iterrows():
    if row[4] == "Red":
        row[6] = row[0]
        row[7] = row[1]
    elif row[4] == "Blue":
        row[7] = row[0]
        row[6] = row[1]

match_df

,red,blue,date,location,win_color,weight_class,winner,loser
0,Henry Cejudo,Marlon Moraes,2019-06-08,"Chicago, Illinois, USA",Red,Bantamweight,Henry Cejudo,Marlon Moraes
1,Valentina Shevchenko,Jessica Eye,2019-06-08,"Chicago, Illinois, USA",Red,Women's Flyweight,Valentina Shevchenko,Jessica Eye
2,Tony Ferguson,Donald Cerrone,2019-06-08,"Chicago, Illinois, USA",Red,Lightweight,Tony Ferguson,Donald Cerrone
3,Jimmie Rivera,Petr Yan,2019-06-08,"Chicago, Illinois, USA",Blue,Bantamweight,Petr Yan,Jimmie Rivera
4,Tai Tuivasa,Blagoy Ivanov,2019-06-08,"Chicago, Illinois, USA",Blue,Heavyweight,Blagoy Ivanov,Tai Tuivasa
...,...,...,...,...,...,...,...,...
5139,Gerard Gordeau,Kevin Rosier,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,Gerard Gordeau,Kevin Rosier
5140,Ken Shamrock,Patrick Smith,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,Ken Shamrock,Patrick Smith
5141,Royce Gracie,Art Jimmerson,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,Royce Gracie,Art Jimmerson
5142,Kevin Rosier,Zane Frazier,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,Kevin Rosier,Zane Frazier
5143,Gerard Gordeau,Teila Tuli,1993-11-12,"Denver, Colorado, USA",Red,Open Weight,Gerard Gordeau,Teila Tuli

In [11]:
transformed_match_df = match_df[["date","location","weight_class","winner","loser"]]

transformed_match_df

,date,location,weight_class,winner,loser
0,2019-06-08,"Chicago, Illinois, USA",Bantamweight,Henry Cejudo,Marlon Moraes
1,2019-06-08,"Chicago, Illinois, USA",Women's Flyweight,Valentina Shevchenko,Jessica Eye
2,2019-06-08,"Chicago, Illinois, USA",Lightweight,Tony Ferguson,Donald Cerrone
3,2019-06-08,"Chicago, Illinois, USA",Bantamweight,Petr Yan,Jimmie Rivera
4,2019-06-08,"Chicago, Illinois, USA",Heavyweight,Blagoy Ivanov,Tai Tuivasa
...,...,...,...,...,...
5139,1993-11-12,"Denver, Colorado, USA",Open Weight,Gerard Gordeau,Kevin Rosier
5140,1993-11-12,"Denver, Colorado, USA",Open Weight,Ken Shamrock,Patrick Smith
5141,1993-11-12,"Denver, Colorado, USA",Open Weight,Royce Gracie,Art Jimmerson
5142,1993-11-12,"Denver, Colorado, USA",Open Weight,Kevin Rosier,Zane Frazier
5143,1993-11-12,"Denver, Colorado, USA",Open Weight,Gerard Gordeau,Teila Tuli

In [12]:
fighter_data = pd.read_csv(fighter_path)

In [15]:
fighter_df = fighter_data.iloc[:,:3]

fighter_df

          fighter_name  Height    Weight
0           AJ Fonseca   5' 4"  145 lbs.
1          AJ Matthews  5' 11"  185 lbs.
2             AJ McKee  5' 10"  145 lbs.
3            AJ Siscoe   5' 7"  135 lbs.
4           Aalon Cruz   6' 0"  145 lbs.
...                ...     ...       ...
3308     Zelim Imadaev   6' 0"  170 lbs.
3309      Zhang Lipeng  5' 11"  155 lbs.
3310     Zoila Frausto   5' 4"  135 lbs.
3311        Zu Anyanwu   6' 1"  251 lbs.
3312  Zubaira Tukhugov   5' 8"  145 lbs.

[3313 rows x 3 columns]